# Método a emplear: cellIdx || fBruta
method: "cellIdx"
randomize: true

# N, L, R
totalParticles: 1000
boardLength: 150.0
maxR: 5.0

# Archivos de entrada
staticFile: "sds-tp1/src/main/resources/static.txt"
dynamicFile: "sds-tp1/src/main/resources/dynamic.txt"

# Rc y condición de borde
radius: 5.0
periodicOutline: true

# 0 si quiero el óptimo
M: 0

# Default: output.txt
fileName: ""