# Método a emplear: cellIdx || fBruta
method: "cellIdx"
randomize: false

# N y L
totalParticles: 200
boardLength: 70.0

# Archivos de entrada
staticFile: "sds-tp1/src/main/resources/static.txt"
dynamicFile: "sds-tp1/src/main/resources/dynamic.txt"

radius: 0.5
periodicOutline: true

# 0 si quiero el óptimo
M: 2

# Default: output.txt
fileName: ""