# Método a emplear: cellIdx || fBruta
method: "cellIdx"
randomize: true

# N y L
totalParticles: 200
boardLength: 70.0

# Archivos de entrada
staticFile: "filename1"
dinamicFile: "filename2"

radius: 0.98
periodicOutline: true

# 0 si quiero el óptimo
M: 10

# Default: output.txt
fileName: ""